### ISSUE TITLE
lint@v1 action requires `dir-name` even though it should be optional

### ISSUE THREAD

**Issue by till** [ariga/atlas-action#112]
Seems like it's fixed in master, but not relased?

`action.yml` says required `false`:
https://github.com/ariga/atlas-action/blob/master/migrate/lint/action.yml#L12-L14

**Comment by till** [comment]
It seems like the error is not in the action's direct code, but in the `ariga-atlas`:
https://github.com/ariga/atlas-action/blob/master/atlasaction/action.go#L93

It it save to assume that the linting "only" works with an account on atlas.io? I wasn't aware of that.

**Comment by rotemtam** [comment]
The current lint action requires an Atlas Cloud token, yes. You can always cook your own by manually running atlas migrate lint if that doesn't work for you 🙏

**Comment by till** [comment]
@rotemtam makes sense, I think the `action.yml` should be fixed then to make it more obvious that the inputs are required.

**Comment by masseelch** [comment]
> I think the `action.yml` should be fixed then to make it more obvious that the inputs are required

The values can be given to atlas by using an `atlas.hcl` configuration file. Therefore, they can not be required here.

**Comment by clarkedb** [comment]
> The current lint action requires an Atlas Cloud token, yes. You can always cook your own by manually running atlas migrate lint if that doesn't work for you 🙏

@rotemtam Is there a specific reason that the action has been modified to only be useful to those using Atlas Cloud? Pre-v1 this worked for people not using Atlas Cloud.

**Comment by rotemtam** [comment]
hey @clarkedb 

Thanks for reaching out. Great question - here's the gist of it: 

Last October, we did a [full revamp](https://atlasgo.io/blog/2023/10/12/atlas-actions-v1) of the whole Atlas GH Actions codebase.  As part of that change we deprecated the old `atlas-action` which was written in TypeScript and longer seriously maintained.

As you probably know, Atlas is backed by [Ariga](https://ariga.io), a commercial company. Our team is very small and so we try to be laser-focused on work that will bring Atlas to sustainable success. In other words, the less we do, the better we can do it, and the more likely we are to build something that sticks for the very long run.  For this reason, we also deprecated the old acions on that same occasion. 

Regarding the action CI flow, we think the cloud-connected flow is much better and has critical technical capabilities like detecting [Non Linear Change](https://atlasgo.io/lint/analyzers#non-linear-changes) that are dependent on having external state available for calculations. 

If for any reason you cannot use the free Atlas Cloud tier, you can always simply call `atlas migrate lint` from any normal GitHub Actions Workflow and get a similar result. 

I hope this answers your question

**Comment by advdv** [comment]
@masseelch Sorry to hijack this, but you mention:

> > I think the `action.yml` should be fixed then to make it more obvious that the inputs are required
> 
> The values can be given to atlas by using an `atlas.hcl` configuration file. Therefore, they can not be required here.
> 
> https://github.com/ariga/atlas-action#inputs-2

But, i cannot find how to do this in the reference documentation of the hcl configuration. Could you tell me what configuration i need to set in order to do this in the atlas.hcl?

**Comment by masseelch** [comment]
https://atlasgo.io/atlas-schema/projects

In here you can see all options for the config file. Anything specific you want to know?

**Comment by advdv** [comment]
> https://atlasgo.io/atlas-schema/projects
> 
> In here you can see all options for the config file. Anything specific you want to know?

Thank you for the quick reply, but i know of this page. I read every part of the documentation back to front. I mean:
- I have a project on atlas cloud called "ccvmodel" (see screenshot)
- i want to run the migration/lint action 
- but i do NOT want to specify "dir-name: "ccvmodel" in the github action, i want to sepcify it in the atlas.hcl
- what configuration can i use in the atlas.hcl to achieve this? 

![image](https://github.com/user-attachments/assets/4b6ccc5d-5f79-4e3d-9ceb-fc48f87b3a5d)

**Comment by giautm** [comment]
> * but i do NOT want to specify "dir-name: "ccvmodel" in the github action, i want to sepcify it in the atlas.hcl

Hello @advdv, the `dir-name` is required because the `migrate/lint` action used it as [the `base` flag](https://github.com/ariga/atlas-action/blob/0c3d8ed3489e082cead8fe2b8ee773b30838d787/atlasaction/action.go#L493) for checking new migration files. default is `atlas://<dir-name>?tag=latest`, this `base` argument was not support in the atlas.hcl yet.

**Comment by advdv** [comment]
Ah ok, i must have misunderstood that this was possible. No problem. Thank you for the link to the source code, that is actually super usefull to understand how the github actions map onto the Atlas CLI.
