### ISSUE TITLE
Error: slug must be lowercase alphanumeric and may contain /.-_

### ISSUE THREAD

**Issue by xbreid** [ariga/atlas-action#142]
Hello,

I was attempting to migrate to the new CI/CD workflows and noticed a bug in `ariga/atlas-action/migrate/lint@v1`.

The error was provided: `Error: slug must be lowercase alphanumeric and may contain /.-_`

From what I can gather, my `dir-name` unfortunately has uppercase characters, and is causing the linting action to fail.

**Comment by rotemtam** [comment]
Use your dir slug , you should be able to find it in the project page, the part or the URL after atlas://

![image](https://github.com/ariga/atlas-action/assets/1522681/763c5ce8-dc61-4291-b4b1-8ec5627a525c)

**Comment by giautm** [comment]
Hello @xbreid, please try to rename your directory on the Setting page. Convert its name to only lowercase character and try again. If it doesn't help, please let me know with more detail (tenant / dir's name via) - privately. So, I can help you on our side.

**Comment by xbreid** [comment]
@giautm thanks! reached out to you on Discord.
