### ISSUE TITLE
Meet unexpected errors

### ISSUE THREAD

**Issue by VoVAllen** [ariga/atlas-action#43]
link: https://github.com/tensorchord/envd-server/actions/runs/3648121383/jobs/6161170673

Message:
```
Error: Resource not accessible by integration
```

**Comment by giautm** [comment]
Hello @VoVAllen, I think the issue is related to the permission of the workflow. Atlas need the write permission to comment on the PR. Can you try again with bellow config?

```yaml
permissions:
  pull-requests: write
```

**Comment by VoVAllen** [comment]
@giautm Thanks! I think it should be mentioned in the doc and also make it configurable

**Comment by giautm** [comment]
The permissions still not correct, it's read-only

<img width="384" alt="Screenshot 2022-12-08 at 20 21 35" src="https://user-images.githubusercontent.com/12751435/206457059-3b189791-c8a9-4e14-ad37-aa113ca592d6.png">
<img width="383" alt="Screenshot 2022-12-08 at 20 21 13" src="https://user-images.githubusercontent.com/12751435/206457073-5103b03a-a212-4920-ad00-fb329afb9392.png">

**Comment by masseelch** [comment]
Does not look like a bug in this code.
