### ISSUE TITLE
Fix atlas version

### ISSUE THREAD

**Issue by piotratlz** [ariga/atlas-action#55]
Is it possible to fix atlas CLI version to be used during action run?
It seems that currently latest atlas is used.

**Comment by giautm** [comment]
Hello @piotratlz, please explain your use-case. Do you want to use a fixed version of atlas in the Action?

**Comment by piotratlz** [comment]
Hi @giautm, this is exactly the thing I'm trying to achieve.
I'm not much familiar with GH actions and I couldn't find action configuration.
Thank you your response, this thread can be closed.
