### ISSUE TITLE
Allow destructive change

### ISSUE THREAD

**Issue by Galaf** [ariga/atlas-action#57]
Hello!

I'd like to drop a table on purpose but I get the error `DS102` which is expected.
How can I instruct Atlas on letting this go because it's on purpose?

Thank you for your time!

**Comment by rotemtam** [comment]
Hi @Galaf,

Thanks for reaching out. 

Thanks for reaching out. Use the `nolint` directive: 
https://atlasgo.io/versioned/lint#nolint-directive

Closing.

**Comment by Galaf** [comment]
Thank you, it worked!
