### ISSUE TITLE
How to fail the GHA workflow if backwards incompatible changes detected?

### ISSUE THREAD

**Issue by dimber-cais** [ariga/atlas-action#58]
When the action runs I can see it correctly detects backwards incompatible changes. 

However, I wasn't able to work out how to cause a non-zero exit code, which could then be used to make the workflow go into a failed state.

If I were running the CLI I would configure an `atlas.hcl` with:
```hcl
lint {
    incompatible {
        error = true
    }
}
```

But there doesn't seem to be a way to pass in an `--config` parameter as an input to this action.

**Comment by rotemtam** [comment]
Hey @dimber-cais 

The action actually predates the flag which is why it isn't supported.

I'll add this flag shortly, in the meantime I think you can apply this use case by placing atlas.hcl in the working-dir for the action (or simply in the repo root)

**Comment by rotemtam** [comment]
Hey @dimber-cais 

This is now supported with the `config` and `config-env` options.
