### ISSUE TITLE
Support install-only

### ISSUE THREAD

**Issue by aplr** [ariga/atlas-action#61]
I'd like to use my re-usable scripts for generating diffs in github actions w/ atlas CLI. I'd like to use the atlas-action to set up atlas for me. However, this does not seem to be supported right now, as:

1. the binary is not exposed for later steps
2. it's not possible to run the atlas-action without executing any command

Do you think it's possible to support that, or with a separate action like `ariga/setup-atlas`?

**Comment by rotemtam** [comment]
We're on it!

**Comment by dorav** [comment]
Hi @aplr 

Thanks for the suggestion, we have implemented the `setup-atlas` action, you can find it here: https://github.com/ariga/setup-atlas/
